In [1]:
import tensorflow as tf 
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
DATADIR="C:/Users/wiN-1o/Desktop/Final_Year_Project/Dataset/dataset/training_set"
CATEGORIES=["cap","imp","inci","mol"]


In [2]:
IMG_SIZE=50

In [3]:
training_data=[]
def create_training_data():
    for category in CATEGORIES:
        path=os.path.join(DATADIR,category)
        class_num=CATEGORIES.index(category)
        print("Category ",class_num,": ",category)
        for img in os.listdir(path):
            img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
            new_array=cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
            training_data.append([new_array,class_num])
            #plt.imshow(new_array,cmap="gray")
            #plt.show()
create_training_data()

Category  0 :  cap
Category  1 :  imp
Category  2 :  inci
Category  3 :  mol


In [4]:
print(len(training_data))

800


In [5]:
import random
random.shuffle(training_data)

In [6]:
for sample in training_data:
    print(sample[1],end=" ")

3 1 0 1 0 1 3 0 0 0 1 3 3 0 0 3 3 3 2 3 2 1 2 1 1 1 3 2 0 0 3 3 1 1 1 3 1 0 2 3 2 0 3 2 0 0 1 0 2 1 2 3 3 2 3 1 1 0 2 0 0 0 1 1 0 0 0 0 1 3 1 0 1 0 3 1 0 1 2 0 0 3 3 1 2 0 1 3 3 3 1 2 2 2 1 0 1 0 0 0 3 0 1 0 1 3 2 3 0 3 1 0 2 0 3 1 1 2 0 0 2 0 2 0 3 1 3 2 1 1 0 3 1 1 2 2 1 1 2 0 0 3 1 0 2 1 2 1 3 3 0 1 0 3 3 2 0 1 0 2 2 3 1 1 2 1 2 2 1 2 3 2 1 0 2 3 3 0 1 0 1 0 2 1 2 1 0 1 2 3 0 1 3 1 3 2 3 2 1 3 0 2 1 2 0 3 1 2 2 1 2 0 2 2 2 1 2 0 0 0 2 3 3 0 3 2 2 0 0 3 2 3 1 0 2 3 1 3 3 2 1 1 1 3 3 0 3 0 3 3 2 3 2 0 2 1 3 3 0 1 0 2 2 2 1 0 0 2 0 2 3 0 2 2 3 1 3 2 3 2 1 1 0 1 2 1 3 1 1 3 0 3 0 0 0 1 3 1 0 3 3 3 1 0 0 1 2 2 1 3 0 0 0 0 1 2 2 3 1 0 2 2 1 3 3 0 3 2 1 2 2 1 0 2 0 0 1 0 3 0 1 1 0 0 3 2 3 3 3 1 2 3 3 0 1 2 3 0 3 3 0 0 3 0 2 2 3 2 1 3 0 3 1 0 3 3 2 0 2 1 3 3 1 0 3 3 2 3 0 1 1 1 1 0 2 2 2 1 2 0 3 1 3 2 2 0 2 3 2 3 1 2 2 1 2 3 2 3 1 0 3 1 0 1 0 3 1 3 1 1 3 1 0 0 3 3 0 2 2 2 3 2 2 2 1 3 0 3 1 2 0 0 0 2 3 2 2 3 2 3 0 3 2 3 2 3 1 2 1 3 3 1 3 0 1 2 3 2 3 3 0 0 2 1 0 1 3 1 2 0 1 0 1 3 3 1 2 2 1 0 

In [7]:
X=[]
Y=[]

for features,labels in training_data:
    X.append(features)
    Y.append(labels)

In [8]:
X=np.array(X).reshape(-1,IMG_SIZE*IMG_SIZE)

X = (X-X.min())/(X.max()-X.min())

In [9]:
np.save('features.npy',X) #saving
np.save('labels.npy',Y)


In [10]:
X=np.load('features.npy')#loading
Y=np.load('labels.npy')

In [11]:
print(X)

[[0.85098039 0.7372549  0.72156863 ... 0.53333333 0.56470588 0.56862745]
 [0.3372549  0.34901961 0.37647059 ... 0.00392157 0.01568627 0.03137255]
 [0.55294118 0.63921569 0.63529412 ... 0.36862745 0.34901961 0.42745098]
 ...
 [0.41176471 0.36078431 0.36470588 ... 0.3372549  0.36470588 0.36078431]
 [0.63921569 0.69803922 0.68235294 ... 0.41176471 0.38039216 0.37647059]
 [0.51764706 0.49803922 0.47058824 ... 0.11372549 0.12156863 0.12941176]]
